from django.http import HttpResponse
from dksim.view.lookupgearfromeighty import gear_lookup


def gear_load(request):
    if request.method == "POST":
        selection = request.POST["eighty"]
        helm, neck, shoulders, chest, waist, legs, boots, wrists, gloves, ring1, ring2, trinket1, trinket2, back, mh_wep, oh_wep, sigil, head_enchant, helm_gem1, helm_gem2, helm_gem3, helm_gem4, helm_gemmeta, neck_gem1, neck_gem2, neck_gem3, neck_gem4, shoulders_enchant, shoulders_gem1, shoulders_gem2, shoulders_gem3, shoulders_gem4, chest_enchant, chest_gem1, chest_gem2, chest_gem3, chest_gem4, waist_gem1, waist_gem2, waist_gem3, waist_gem4, legs_enchant, legs_gem1, legs_gem2, legs_gem3, legs_gem4, boots_enchant, boots_gem1, boots_gem2, boots_gem3, boots_gem4, wrists_enchant, wrists_gem1, wrists_gem2, wrists_gem3, wrists_gem4, gloves_enchant, gloves_gem1, gloves_gem2, gloves_gem3, gloves_gem4, ring1_gem1, ring1_gem2, ring1_gem3, ring1_gem4, ring1_enchant, ring2_gem1, ring2_gem2, ring2_gem3, ring2_gem4, ring2_enchant, trinket1_gem1, trinket1_gem2, trinket1_gem3, trinket1_gem4, trinket2_gem1, trinket2_gem2, trinket2_gem3, trinket2_gem4, back_enchant, back_gem1, back_gem2, back_gem3, back_gem4, mh_wep_enchant, mh_wep_gem1, mh_wep_gem2, mh_wep_gem3, mh_wep_gem4, oh_wep_enchant, oh_wep_gem1, oh_wep_gem2, oh_wep_gem3, oh_wep_gem4 = gear_lookup(eighty_gear_selection = selection)
        all_items_equ = helm + str(",") +  neck + str(",") + shoulders + str(",") + chest + str(",") + waist + str(",") + legs + str(",") + boots + str(",") + wrists + str(",") + gloves + str(",") + ring1 + str(",") + ring2 + str(",") + trinket1 + str(",") + trinket2 + str(",") + back + str(",") + mh_wep + str(",") + oh_wep + str(",") + sigil + str(",") + head_enchant + str(",") + helm_gem1 + str(",") + helm_gem2 + str(",") + helm_gem3 + str(",") + helm_gem4 + str(",") + helm_gemmeta + str(",") + neck_gem1 + str(",") + neck_gem2 + str(",") + neck_gem3 + str(",") + neck_gem4 + str(",") + shoulders_enchant + str(",") + shoulders_gem1 + str(",") + shoulders_gem2 + str(",") + shoulders_gem3 + str(",") + shoulders_gem4 + str(",") + chest_enchant + str(",") + chest_gem1 + str(",") + chest_gem2 + str(",") + chest_gem3 + str(",") + chest_gem4 + str(",") + waist_gem1 + str(",") + waist_gem2 + str(",") + waist_gem3 + str(",") + waist_gem4 + str(",") + legs_enchant + str(",") + legs_gem1 + str(",") + legs_gem2 + str(",") + legs_gem3 + str(",") + legs_gem4 + str(",") + boots_enchant + str(",") + boots_gem1 + str(",") + boots_gem2 + str(",") + boots_gem3 + str(",") + boots_gem4 + str(",") + wrists_enchant + str(",") + wrists_gem1 + str(",") + wrists_gem2 + str(",") + wrists_gem3 + str(",") + wrists_gem4 + str(",") + gloves_enchant + str(",") + gloves_gem1 + str(",") + gloves_gem2 + str(",") + gloves_gem3 + str(",") + gloves_gem4 + str(",") + ring1_gem1 + str(",") + ring1_gem2 + str(",") + ring1_gem3 + str(",") + ring1_gem4 + str(",") + ring1_enchant + str(",") + ring2_gem1 + str(",") + ring2_gem2 + str(",") + ring2_gem3 + str(",") + ring2_gem4 + str(",") + ring2_enchant + str(",") + trinket1_gem1 + str(",") + trinket1_gem2 + str(",") + trinket1_gem3 + str(",") + trinket1_gem4 + str(",") + trinket2_gem1 + str(",") + trinket2_gem2 + str(",") + trinket2_gem3 + str(",") + trinket2_gem4 + str(",") + back_enchant + str(",") + back_gem1 + str(",") + back_gem2 + str(",") + back_gem3 + str(",") + back_gem4 + str(",") + mh_wep_enchant + str(",") + mh_wep_gem1 + str(",") + mh_wep_gem2 + str(",") + mh_wep_gem3 + str(",") + mh_wep_gem4 + str(",") + oh_wep_enchant + str(",") + oh_wep_gem1 + str(",") + oh_wep_gem2 + str(",") + oh_wep_gem3 + str(",") + oh_wep_gem4
    else:
        all_items_equ = "Error"
    return HttpResponse(all_items_equ)
